' Elevated wrapper for rcp.ps1 (Robo-Paste)
' Auto-generated by Install.ps1

Option Explicit

Dim shellApp, shellObj
Set shellApp = CreateObject("Shell.Application")
Set shellObj = CreateObject("WScript.Shell")

If WScript.Arguments.Count = 0 Then
    WScript.Quit 1
End If

Dim folderPath, scriptPath, args
folderPath = WScript.Arguments(0)
scriptPath = "C:\Users\joty79\AppData\Local\RoboCopyContext\rcp.ps1"

folderPath = NormalizePastePathArg(folderPath)
args = "-NoProfile -ExecutionPolicy Bypass -File """ & scriptPath & """ auto auto """ & folderPath & """"
shellApp.ShellExecute "pwsh.exe", args, "", "runas", 1

Function NormalizePastePathArg(pathValue)
    Dim p
    p = Trim(CStr(pathValue))
    If Len(p) = 3 Then
        If Mid(p, 2, 2) = ":\" Then
            ' Avoid Windows argv quote edge-case for drive roots like L:\
            p = p & "."
        End If
    End If
    NormalizePastePathArg = Replace(p, """", """""")
End Function
